# Generated by Django 5.2.16 on 2026-09-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_history", "0004_alter_distributionbaseline_salesperson_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientportfoliosnapshot",
            name="nk_supervisor",
        ),
    ]
