# Generated by Django 5.2.16 on 2026-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0006_ferista_allows_multiple_covered"),
    ]

    operations = [
        migrations.AddField(
            model_name="hierarchynode",
            name="is_representante",
            field=models.BooleanField(default=False),
        ),
    ]
